const mongoose = require('mongoose');

// Short-lived 6-digit OTP generated by a hospital to invite a doctor or nurse.
// The OTP is stored as a SHA-256 hex digest so the plain value is never persisted.
// MongoDB TTL index auto-deletes expired documents.
const hospitalOTPSchema = new mongoose.Schema(
  {
    hospitalId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Hospital',
      required: true
    },
    // SHA-256(plainOTP) — deterministic, so lookup by hash works
    otpHash: {
      type: String,
      required: true
    },
    targetRole: {
      type: String,
      enum: ['doctor', 'nurse'],
      required: true
    },
    expiresAt: {
      type: Date,
      required: true
    },
    used: {
      type: Boolean,
      default: false
    },
    usedBy: {
      type: mongoose.Schema.Types.ObjectId
    }
  },
  { timestamps: true }
);

// MongoDB TTL: auto-purge documents once expiresAt is past
hospitalOTPSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

module.exports = mongoose.model('HospitalOTP', hospitalOTPSchema);
