const mongoose = require('mongoose');

// Short-lived 6-digit OTP generated by a patient to grant a doctor access.
// Stored as SHA-256 hex digest. MongoDB TTL auto-deletes expired docs.
const patientAccessOTPSchema = new mongoose.Schema({
  patient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  otpHash: {
    type: String,
    required: true
  },
  expiresAt: {
    type: Date,
    required: true
  },
  used: {
    type: Boolean,
    default: false
  },
  usedByDoctor: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Doctor'
  }
}, { timestamps: true });

// Auto-purge expired OTPs
patientAccessOTPSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

module.exports = mongoose.model('PatientAccessOTP', patientAccessOTPSchema);
